---
title: "Regression Architect Documentation"
author: "Anurag Ladage"
date: "October 20, 2014"
output: html_document
---


###**Summary:**
This application is a simple app to build regression models. The application can perform either *Multiple linear Regression*, *Logistics Regression* or *Poisson Regression* on any clean dataset (in .csv format) uploaded by the user. It uses Alkaike Information Criterion (AIC) or Bayesian Information Criterion(BIC) to build the best possible regression model for you. The application also gives an option to plot the residual plots and the response variable plot for users wanting to perform an indept analysis.All the document and R files related to this application can be found in the github repository mentioned below.


###**General Procedure:**

  1. Upload a clean dataset without any missing values in comma separated values format (.csv).

  2. Select the regression technique to be implemented.
  
  3. Select the model selection criteria.

  4. Enter the column name of the response variable.

  5. Build the regression model by pressing the action button *"Create Regression Model"*.

  6. Further, the predicted response variable value can be plotted over the actual response variable value by pressing *"Plot Response Variables"* button.

  7. Additionally, the residual plot can also be plotted using the *"Create Residual Plots"* action button for indepth analysis the residuals.


###**Do's and Dont's:**

  1. Upload only datasets with no missing values and in .csv format.
  
  2. Please upload medium sized datasets if possible for testing the application as AIC and BIC solve different models iteratively and the solving time will increase with the increase in the numner of independent variables.
  
  3. The application hasn't been configured for all possible error handling situations thus, care should be taken to apply the regression techniques to proper type of response variable as suggested below:
  
    + If your response variable is a real number having continuous values multiple linear regression is your best option.
  
    + If the response variable is a binary variable, then logistics regression should be used.
  
    + Poisson regression should be used for a response variable which is integer/count by nature and takes on non-negative values.
  
  4. In general BIC is a better model selection criterion than AIC.
  
  5. While creating a .csv file from a R dataset, please make sure to set the row.names parameter to FALSE in write.csv() function.
  
  
###**Sample Datasets:**
The above application has been tested on the following datasets. Feel free to download and use them to test this app.

 * [mtcars](https://github.com/GriMMJaW/REGRESSION-ARCHITECT-APPLICATION/blob/master/mtcars.csv)
 * [pima.tr](https://github.com/GriMMJaW/REGRESSION-ARCHITECT-APPLICATION/blob/master/pima.csv)
 * [iris](https://github.com/GriMMJaW/REGRESSION-ARCHITECT-APPLICATION/blob/master/iris.csv)

###**Sample Model Examples:**
1. **Multiple Linear Regression:** From the mtcars dataset select *'mpg'* as the response variable perform regression analysis to see the outputs.

2. **Linear Logistics Regression:** From the pima.tr dataset select *'type'* as the response variable and perform the analysis.

3. **Poisson Regression:** From the pima.tr dataset select *'age'* as the response variable and peform this regression analysis



###Github Link: 
* [Regression Architect Github Repository](https://github.com/GriMMJaW/REGRESSION-ARCHITECT-APPLICATION)